### ISSUE TITLE
Future improvement: Automatic CMakeLists creation

### ISSUE THREAD

**Issue by ruipimentelfigueiredo** [vislab-tecnico-lisboa/yarp-bottle-generator#14]
@mikearagao, we did some changes on your code in order to allow the generation of several codes using the yarp-bottle-generator. Now, the configuration file and the generated file are parameters of the yarp-bottle-generator. It creates a folder for each new file, which is inside the results folder.

However, as a future improvement, the CMakeLists could be generated automatically to facilitate the compilation of the generated code.

**Comment by mikearagao** [comment]
@ruipimentelfigueiredo that's awesome! Really glad that someone is looking at the code! I'll gladly help you with any doubts.

And yes, I guess it is important to generate the CMakeLists to compile the generated code in order to keep an easy flow.

**Comment by plinioMoreno** [comment]
This improvement was included in the commit e7ec69b54ef9da1d3342cd7e6e02621556d0f84c.
