### ISSUE TITLE
Add support for correct ROS timestamp

### ISSUE THREAD

**Issue by plinioMoreno** [vislab-tecnico-lisboa/yarp-bottle-generator#15]
Currently only the seconds field of the ROS time value is filled.
The remaining of the time value is set to 100......This should be changed to the actual remaining of the time value

**Comment by mikearagao** [comment]
True @plinioMoreno... And I believe the units are not the same as the ones in ROS, not sure though!

**Comment by plinioMoreno** [comment]
The [commit](https://github.com/vislab-tecnico-lisboa/yarp-bottle-generator/commit/f7e29fabde1c1f62f7574b3964991ad8a55f4356) solves this problem at [file](https://github.com/vislab-tecnico-lisboa/yarp-bottle-generator/commit/f7e29fabde1c1f62f7574b3964991ad8a55f4356#diff-4ac2698e5ee603b916848482fea07b21). Thanks to @ruipimentelfigueiredo for helping with this!
